### ISSUE TITLE
[Technical story] Server setup and domain

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#19]
We need to have a server to run this site. These are the requirements:

* Drupal 7 (see full requirements [here](http://drupal.org/requirements)):
 * MySQL 5.0.15/MariaDB 5.1.44
 * PHP 5.2.5 or higher (5.4 or higher recommended)
 * PHP requirements (at least 32MB, 128 is recommended): https://www.drupal.org/requirements/php
* Webserver: https://www.drupal.org/requirements/webserver
* Database server: https://www.drupal.org/requirements/database
* GIT
* Shell access
* ideally: drush (drupal command line) see [installation instructions here](http://docs.drush.org/en/master/install/)

**Comment by skotperez** [comment]
I've read the Drupal software requirements in the link you posted, but i cannot find there any hardware requirements. According to your experience, which are the minimum resources (RAM, CPU) to start with?

In relation to SSH access, do you need any special package to work with?

**Comment by ccamara** [comment]
Ha! Good questions, @skotperez! You're right there are no hardware requirements in the official documentation, so I do not have any idea about it. What I can say is that I have uploaded the issue's description with information about PHP, Webserver and Database server and I am currently I am running it on my shared server with the following configuration:

* OS: Ubuntu 12.04
* Apache webserver
* Mysql
* CPU: AMD opteron
* RAM: 256MB
* PHP Max memory limit: 90MB

I do not have any clue on your question about SSH , neither :( (what a bad sysadmin would I be!)

**Comment by ccamara** [comment]
Additionally I do not have any experience on using drupal as a service, so maybe @Ale- may have a thought on this

**Comment by Ale-** [comment]
Hi! 
There isn't any special hardware requirement to services to be run. Only take into account the drupal version. If you want to use Drupal 8 (with services in core) you'll need an updated version of PHP.

**Comment by skotperez** [comment]
The server is set up. @ccamara I send you the credentials privately. @Ale- if you want to access, let me know.

**Comment by ccamara** [comment]
Server is up and running and website has been installed and publicly accessible from: http://new.cadaversinmobiliarios.org

Closing this issue, thanks @skotperez and @Ale- !
