### ISSUE TITLE
Enable antispam solution

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#29]
Consider these options:

* [Mollom](http://dgo.to/mollom Offers): spam protection through their freemium service.
* [Honey Pot](https://www.drupal.org/project/honeypot)
* [CAPTCHA](https://www.drupal.org/project/captcha) - A simple image-based CAPTCHA builder.
* [reCAPTCHA](https://www.drupal.org/project/recaptcha) - Implements reCAPTCHA for image-based CAPTCHAs.
* [BOTCHA](https://www.drupal.org/project/botcha) - Has many different bot-defeating recipes.

Exhaustive comparison of modules: https://groups.drupal.org/node/77093

**Comment by ccamara** [comment]
@skotperez do you have good experiences in antispam services/solutions?

**Comment by skotperez** [comment]
I prefer local antispam systems with no need to remote connection. reCapthcha is not. I don't know honeypot. A simple question and answer system do the job: http://montera34.com/contacto/

**Comment by ccamara** [comment]
Used honeypot for the moment.
