### ISSUE TITLE
As an editor I want to be able to manage content and taxonomies

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#33]
* [x] Create an editor role
* Grant editors with the following permissions
 * [x] Manage taxonomy
 * [x] Manage content types
 * [x] Revert revisions
 * [x] Delete any node

**Comment by ccamara** [comment]
@numeroteca can you access to new.cadaveresinmobiliarios.org and confirm that you can:

- Access http://new.cadaveresinmobiliarios.org/es/admin/content and see a list of published content 
- edit any content
- delete any content
- revert any revision (you may need to edit a corpse and you'll se a "history" or "revisions" tab, which you should click)
- access http://new.cadaveresinmobiliarios.org/es/admin/structure/taxonomy and see a list of vocabularies and terms and add new ones or edit existing ones 

If you can do everything (as expected) you can close the issue.

**Comment by numeroteca** [comment]
I've got the power, everything works great (but I am not allowed to close this issue).

**Comment by ccamara** [comment]
> I've got the power

LOL.

Closing this issue. Don't know why you don't have permissions to close it (maybe because I am the one who created this issue?)

**Comment by numeroteca** [comment]
I am able to close my own issues but not to assign labels to them.
