### ISSUE TITLE
Create a translator role

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#38]
Grant permissions for translating everything.

**Comment by ccamara** [comment]
@numeroteca can you confirm that you can access to this page and translate the interface? -> http://new.cadaveresinmobiliarios.org/es/admin/config/regional/translate/translate

Can you tell me if you have a menu with easy access to that path?

If the answer to both questions is yes, feel free to close this issue.

**Comment by numeroteca** [comment]
I can access the url but I have no rights to translate. 
When I go to edit a term I get "Esta es una cadena definida por el usuario. Usted no dispone de permisos para traducir este tipo de cadenas."

**Comment by ccamara** [comment]
Try now, @numeroteca

**Comment by numeroteca** [comment]
If I go to http://new.cadaveresinmobiliarios.org/es/admin/config/regional/translate/translate I get "Acceso denegado. Usted no está autorizado para visitar esta página."

**Comment by ccamara** [comment]
It should be working now. Can you confirm, @numeroteca ?

**Comment by numeroteca** [comment]
No it works!
Yeas and yes!

I don't have yet the rights to close this thread.

**Comment by ccamara** [comment]
Glad to hear that! Closing this issue.
