### ISSUE TITLE
Ok with these warnings after install?

### ISSUE THREAD

**Issue by numeroteca** [cadaveresinmob/c_inmobiliarios#47]
Estaba instalando Drupal de cero y tardó mucho tiempo en esta posición: 0% en "Starting import".
![fallo_drupal_install_importing](https://cloud.githubusercontent.com/assets/1223722/14802247/1f3518d2-0b50-11e6-8930-45f447264333.png)
¿Alguna idea de qué puede ser?

El proceso terminó y me dio estos warning:

```
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "create blog_post content".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete any blog_post content".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete own blog_post content".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in blog_category".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_building_type".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_category".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_contractor".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_court".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_politician".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_promoter".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_source".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_status".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_technician".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_type".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in corpse_use".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in financial_entities".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "delete terms in tags".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit any blog_post content".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit own blog_post content".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in blog_category".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_building_type".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_category".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_contractor".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_court".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_politician".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_promoter".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_source".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_status".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_technician".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_type".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in corpse_use".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in financial_entities".
    Warning in features rebuild of ft_c_inmobiliarios_core. No module defines permission "edit terms in tags".
    All necessary changes to sites/default and sites/default/settings.php have been made, so you should remove write permissions to them now in order to avoid security risks. If you are unsure how to do so, consult the online handbook.
```

y un warning en rojo

`Warning: file_put_contents(private:///.htaccess): failed to open stream: "DrupalPrivateStreamWrapper::stream_open" call failed in file_create_htaccess() (line 494 of /home/numeroteca/sites/c_inmobiliarios/docroot/includes/file.inc).`

¿es normal?

**Comment by ccamara** [comment]
No es normal, no... Aunque no tiene mayor importancia, hace que la instalación tarde muchísimo (45 minutos en mi viejo ordenador), y que se cree una carpeta que no debería crearse, entre otras cosas. Sospecho que está telacionado con #1 pero no estoy seguro.

Busco a ver si encuentro la solución.

**Comment by ccamara** [comment]
Confirmo que el problema del warning `Warning: file_put_contents(private:///.htaccess): failed to open stream: "DrupalPrivateStreamWrapper::stream_open" call failed in file_create_htaccess() (line 494 of /home/numeroteca/sites/c_inmobiliarios/docroot/includes/file.inc).` lo introduje en el commit 831e353. He creado este otro 96737f1 deshaciendo esos cambios, aunque no está aún rebaseado en la rama master. Eso implica que 1) tengo que resolver los otros problemas relacionados con la instalación y 2) la issue #1 estará abierta de nuevo.

**Comment by numeroteca** [comment]
Ya nos dices si el problema es crucial, o si mejor es centrarse en otros temas.

**Comment by ccamara** [comment]
Estoy en ello ahora mismo. El problema de los warnings en sí no es crucial pero hace que la instalación sea muy lenta en local. Los warnings vienen de que he guardado unos permisos para cosas que aún no existen (crear, editar... posts de blog), así que imagino que será algo del orden en el que se cargan las features. Tendré que mirar por ahí. 

Por otra parte he tardad mucho porque mi instalación local ha empezado a petar de golpe y me ha costado ver que A) es debido a que he actualizado a Kubuntu 16.04 que trae php7 en lugar de 5 y que B) el módulo field_group que utilizamos da problemas con esta versión de php. Por suerte acabo de aplicar este patch https://www.drupal.org/node/2649648#comment-10744842 y funciona en mi local, así que en breve subiré el cambio (que por otra parte no afecta a nuestra instalación, pues corre sobre php5 -eso me dio la pista)

**Comment by ccamara** [comment]
Problemas resueltos: ya no hay ningún warning molesto y el tiempo de instalación se ha reducido considerablemente. De momento habrá que activar manualmente las copias de seguridad diarias de la base de datos.
