### ISSUE TITLE
¿Cómo importar los datos de /data a la instalación de Drupal?

### ISSUE THREAD

**Issue by numeroteca** [cadaveresinmob/c_inmobiliarios#48]

**Comment by ccamara** [comment]
Es normal que tras hacer la instalación no estén los contenidos: solo se ha instalado todo lo que tiene que ver con configuración, pero no hay nada de contenido. (Está pensado para utilizar de cero, no ser una copia de una base de datos). 

Ahora bien: puedes importar rápidamente los contenidos accediendo a la url `<dominio>/import`. Verás que hay dos importadores creados, uno para nación rotonda y otro para lo demás (son distintos porque los campos son distintos). Haz clic en alguno de ellos y adjunta el csv correspondiente (Están todos en la carpeta `/data` de la raiz del proyecto). Respecto a los CSV, hace tiempo que no los actualizo, pero no será problema de momento (tengo[ estos scripts en R](https://github.com/ccamara/c_inmobiliarios_data) que se conectan al drive y lo montan todo para tener siempre la última versión y hacer las manipulaciones necesarias para importarlos)
