### ISSUE TITLE
As a visitor I want to fill in all information about an urban corpse

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#5]
Create a content type with the following fields:

1. [x] `nombre_promocional`
1. [x] `nombre_urbanistico`
1. [x] `latitud_longitud`
1. [x] `direccion`
1. [x] `municipio`
1. [x] `provincia`	
1. [x] `comunidad_autonoma`
1. [x] `tipologia_asentamiento_principal`
1. [x] `tipologia_asentamiento_secundario` (tipología de asentamiento admite varios valores)	
1. [x] `fuente` (es una taxonomía)	
1. [x] `enlace_web`
1. [x] `enlance_a_mapa_foto_aerea` decidir si vale la pena crearlo
1. [x] `fecha_autor_fuente_de_la_foto` decidir si vale la pena crearlo
1. [x] `padre_adoptivo` ahora es un user reference, quizá no sea la mejor opción presente por tema de importaciones
1. [x] `superficie_terreno`	
1. [x] `superficie_construida`
1. [x] `suelo_ocupado_actual`
1. [x] `viviendas_construidas`
1. [x] `plazas_hoteleras_construidas`
1. [x] `parcelas_uso_industrial_construidas`
1. [x] `parcelas_uso_comercial_construidas`
1. [x] `parcelas_uso_equipamiento_construidas`
1. [x] `estado_actual`
1. [x] `comentarios_otras_opciones` decidir si vale la pena crearlo
1. [x] `promotor`
1. [x] `constructor`
1. [x] `arquitecto_o_tecnico_redactor`
1. [x] `descripcion_propiedad` decidir si vale la pena crearlo
1. [x] `ubicacion_codigo_ine_municipio`
1. [x] `ubicacion_codigo_ine_provincia`
1. [x] `uso`
1. [x] `comentarios_otros` decidir si vale la pena crearlo
1. [x] `tipologia_edificatoria`
1. [x] `comentarios_tipologia`	
1. [x] `edificabilidad_absoluta_planificada_o_aprobada`
1. [x] `viviendas_aprobadas_en_planeamiento`
1. [x] `plazas_hoteleras_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_industrial_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_comercial_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_equipamiento_aprobadas_planeamiento`
1. [x] `numero_habitantes_previsto_planeamiento` (Calculado a partir del número de viviendas)
1. [x] `numero_de_visitantes_previsto_aplicable_centros_de_ocio_planeamiento` 
1. [x] `convenio_urbanistico_planeamiento_fecha_licencia` (fecha)
1. [x] `plan_parcial_planeamiento_fecha_licencia` (fecha)
1. [x] `modificacion_pgou_planeamiento_fecha_licencia` (fecha)
1. [x] `proyecto_urbanistico_planeamiento_fecha_licencia` (fecha)
1. [x] `licencia_obras_planeamiento_fecha_licencia` (fecha)
1. [x] `otras_fechas_planeamiento_fecha_licencia` (3 valores, no todos son fechas porque incluyen descripción)
1. [x] `convenio_urbanistico_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor)
1. [x] `plan_parcial_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor separado por comas. Hay que modificar una Y)
1. [x] `modificacion_pgou_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor)
1. [x] `proyecto_urbanistico_planeamiento_tecnico_redactor` (1 Item, Texto o taxonomia?) 
1. [x] `licencia_obras_planeamiento_tecnico_redactor` (ningún item)
1. [x] `otros_planeamiento_tecnico_redacto` (1 item, texto curioso)
1. [x] `convenio_urbanistico_politica` (ningún item)
1. [x] `plan_parcial_urbanistico_politica` (ningún item)
1. [x] `modificacion_urbanistico_politica` (ningún item)
1. [x] `proyecto_urbanistico_politica` (ningún item)
1. [x] `licencia_urbanistico_politica` (ningún item)
1. [x] `otros_urbanistico_politica` (ningún item)
1. [x] `recursos_interpuestos` (1 item, texto largo)
1. [x] `sentencias_judiciales` (texto largo)
1. [x] `n_fecha_sentencias` 
1. [x] `tribunal_dicta` (2 items. No sé si usar taxonomía libre o texto corto)
1. [x] `fallo`  (1 item lo usa. Texto largo)
1. [x] `hipoteca_cargas`  (1 item lo usa. Texto largo)
1. [x] `cuantia_hipoteca`  (número)
1. [x] `concurso_acreedores`  (3 item usa este campo. Texto largo, es algo confuso su contenido)
1. [x] `entidades_financieras`  (2 items. Taxonomía de valores múltiples)
1. [x] `figuras_proteccion_ambiental` (2 elemento usa este campo, parece que se solapa con el campo `zonificacion_nivel_proteccion` , campo de texto largo )
1. [x] `nombre_figuras_proteccion_ambiental` (ningún item usa este campo)
1. [x] `zonificacion_nivel_proteccion` (2 items lo utilizan, campo de texto largo)
1. [x] `dominio_publico` (Solo un item tiene un valor)
1. [x] `enlaces_noticias`
1. [x] -`material_grafico`- (fusionado con el campo URL)
1. [x] `archivos_adjuntos` (File field)

Grant permissions to
* [x] anonymous to create new urban corpses.
* [x] registered users to edit urban corpses

**Comment by ccamara** [comment]
Working on it

**Comment by ccamara** [comment]
Initial work has been done. Edited issue's description to display which fields have already been created.

**Comment by ccamara** [comment]
Updated description.

**Comment by skotperez** [comment]
@numeroteca it is necessary to check fields list above to see which one to import. All fields checked are now included in the parser and ready to be imported.

**Comment by ccamara** [comment]
@numeroteca, the fields that are lacking are:

* all the `comentarios_xxxxx` which doesn't make any sense now,
* the ambiental information, as I do not understand the difference between `figuras_proteccion_ambiental`,  `zonificacion_nivel_proteccion` and `nombre_figuras_proteccion_ambiental`
* `material_grafico` , which I do not know if it makes sense now. (We already have a file field where files can be uploaded)

**Comment by numeroteca** [comment]
I see that many items need clarification. Here I give answers to the ones commented above, for others I'll review in a separete place, para otros necesitaremos hablar con Eugenia y Julia:

**comentarios_**: In `comentarios_otras_opciones` there are plenty of useful comments. All of these fields (comentarios_xxx) have been used to provide extra information or clarify other fields.
In https://cadaveresinmobiliarios.cartodb.com/tables/base_datos_cadaveres_inmobiliarios_02_02_2016/public you can see all the values that are in the field. 
`comentarios_otras_opciones` has been used to store all the non structured extra information that came from adoptions.
It is explained in [the first tab row seven](https://docs.google.com/spreadsheets/d/1nX0ZQK8I3lg2BO1i0bNsHi6-gGD0OorBNMzoz0o1VsU/edit#gid=945610373): "Si en la selección anterior no encuentras el estado actual que más ase ajusta a tu cadáver, puedes escribirlo aquí o completar con un comentario la selección anterior", "Puedes agregar en esta celda, los usos complementarios permitidos para el sector", "Puedes agregar en esta celda, las tipologías complementarias permitidas para el sector".

Maybe we should have an open text field for every kind of coment-narrative.

**environmental information**: 
 I'll ask one last time to Rodrigo (ecologistas): he proposed those fields, he might clarify.

**material_grafico**
I agree that it makes no sense to have it now. There are some links in this field (not many). 
However, before loosing them, I'd suggest to add those links to `enlace_web`. Besides: we want to have the possibility to provide url to official documents: is that place `enlace_web`.

**Comment by ccamara** [comment]
I have created a long text field called `Description` into which I have mapped most of the comentarios_ fields (see 4148176).

As per your suggestion I have also mapped `material_grafico` into `url`

Only the ambiental fields are missing and I have to check what kind of field has to be the `dominio_público`, as I used a boolean one and I'm afraid it won't work. Unfortunately there is no description on the google sheet you mentioned before.

**Comment by ccamara** [comment]
As for `dominio_público` only two corpses are using it now. One says "Yes" and the other says "En este caso se trata del Dominio Público.  La realización de obras o trabajos en el Dominio Público Hidráulico y en sus zonas de servidumbre y de policía requerirá autorización previa de la Confederación Hidrográfica del Ebro."

What should we do with it, @numeroteca ?

**Comment by ccamara** [comment]
I have created all the environmental fields as long text fields. Only two corpses are using the Figura de protección field (one saying "Ninguno" and another with a long description) and none is using Nombre de figura de protección.

As far as I am aware only `dominio_publico` needs some clarification and we could close this issue (And almost immediately issues #8 and #15 )

**Comment by numeroteca** [comment]
Estoy en contacto con Ecologistas en Acción, que son los que propusieron estos campos. Os digo cuando sepa algo.

**Comment by numeroteca** [comment]
Así nos cuenta Rodrigo sobre los campos medioambientales:
> Mi propuesta sería:
> * Figuras de protección ambiental: elegir uno o varios entre: [Parque Nacional / Parque Natural, Regional u otras figuras autonómicas de protección / Espacio Red Natura 2000 / Monte protegido por legislación estatal o autonómica / Dominio público hidráulico, pecuario u otros / Figuras de protección municipal o protegido por el planeamiento urbanístico / Otras figuras no contempladas en las anteriores]
> * Nombre y categoría, en su caso: texto libre.
> * Zonificación (nivel de protección): texto libre
> * Dominio público marítimo terrestre: Sí/No
> 
> Espero ser de utilidad.

Si no queda queda claro podemos volver a consultar.

**Comment by ccamara** [comment]
Añadidos los campos. Falta aclarar el enfoque de los campos de superficies y de padres adoptivos. He iniciado [esta discusión en el grupo de correo](https://groups.google.com/forum/#!topic/hacia-base-datos-inmobiliaria/PD-S2XtAzk8) y en cuanto haya un posicionamiento claro podré cerrar esta issue.

**Comment by ccamara** [comment]
Aclarados los aspectos relacionados con los campos que faltaban:

* superficies: el autor del módulo que utilizamos para las superficies (Measured Value Field) ha desarrollado un patch para poder integrarlo con el módulo feeds, que es el que utilizamos para importar los CSV, así que problema resuelto: ¡podemos hacer uso de superficies en distintas unidades sin tener que renunciar a la funcionalidad!

* padres adoptivos: a raiz de la discusión mantenida en el grupo de correo, entiendo que el modelo de "adopción" debería ser el de la wikipedia, es decir: se considerarán padres adoptivos a aquellos quienes hayan hecho algúna edición en el contenido, pudiendo mostrar una lista de esas ediciones. Dado que esa funcionalidad no depende de un campo, sino que tiene que realizarse de forma automática en función de las ediciones hechas en un contenido, el campo es irrelevante. Sin embargo he cambiado el tipo de campo  a uno de taxonomía (commit 57e186e) para poder tener un histórico de los padres adoptivos "legacy".

Cierro la tarea.
