### ISSUE TITLE
As an administrator I want to import already existing "adopted" urban corpses

### ISSUE THREAD

**Issue by ccamara** [cadaveresinmob/c_inmobiliarios#8]
Create a CSV parser to import current data files.

Map the following fields:

1. [x] `nombre_promocional`
1. [x] `nombre_urbanistico`
1. [x] `latitud_longitud`
1. [x] `direccion`
1. [x] `municipio`
1. [x] `provincia`	
1. [x] `comunidad_autonoma`
1. [x] `tipologia_asentamiento_principal`
1. [x] `tipologia_asentamiento_secundario` (tipología de asentamiento admite varios valores)	
1. [x] `fuente` (es una taxonomía)	
1. [x] `enlace_web`
1. [x] `enlance_a_mapa_foto_aerea` decidir si vale la pena crearlo
1. [x] `fecha_autor_fuente_de_la_foto` decidir si vale la pena crearlo
1. [x] `padre_adoptivo` ahora es un user reference, quizá no sea la mejor opción presente por tema de importaciones
1. [x] `superficie_terreno`	
1. [x] `superficie_construida`
1. [x] `suelo_ocupado_actual`
1. [x] `viviendas_construidas`
1. [x] `plazas_hoteleras_construidas`
1. [x] `parcelas_uso_industrial_construidas`
1. [x] `parcelas_uso_comercial_construidas`
1. [x] `parcelas_uso_equipamiento_construidas`
1. [x] `estado_actual`
1. [x] `comentarios_otras_opciones` decidir si vale la pena crearlo
1. [x] `promotor`
1. [x] `constructor`
1. [x] `arquitecto_o_tecnico_redactor`
1. [x] `descripcion_propiedad` decidir si vale la pena crearlo
1. [x] `ubicacion_codigo_ine_municipio`
1. [x] `ubicacion_codigo_ine_provincia`
1. [x] `uso`
1. [x] `comentarios_otros` decidir si vale la pena crearlo
1. [x] `tipologia_edificatoria`
1. [x] `comentarios_tipologia`	
1. [x] `edificabilidad_absoluta_planificada_o_aprobada`
1. [x] `viviendas_aprobadas_en_planeamiento`
1. [x] `plazas_hoteleras_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_industrial_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_comercial_aprobadas_en_planeamiento`
1. [x] `parcelas_uso_equipamiento_aprobadas_planeamiento`
1. [x] `numero_habitantes_previsto_planeamiento`
1. [x] `numero_de_visitantes_previsto_aplicable_centros_de_ocio_planeamiento` estudiar usar computed fields
1. [x] `convenio_urbanistico_planeamiento_fecha_licencia` (fecha)
1. [x] `plan_parcial_planeamiento_fecha_licencia` (fecha)
1. [x] `modificacion_pgou_planeamiento_fecha_licencia` (fecha)
1. [x] `proyecto_urbanistico_planeamiento_fecha_licencia` (fecha)
1. [x] `licencia_obras_planeamiento_fecha_licencia` (fecha)
1. [x] `otras_fechas_planeamiento_fecha_licencia` (3 valores, no todos son fechas porque incluyen descripción)
1. [x] `convenio_urbanistico_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor)
1. [x] `plan_parcial_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor separado por comas. Hay que modificar una Y)
1. [x] `modificacion_pgou_planeamiento_tecnico_redactor` (Texto o taxonomía multivalor)
1. [x] `proyecto_urbanistico_planeamiento_tecnico_redactor` (1 Item, Texto o taxonomia?) 
1. [x] `licencia_obras_planeamiento_tecnico_redactor` (ningún item)
1. [x] `otros_planeamiento_tecnico_redacto` (1 item, texto curioso)
1. [x] `convenio_urbanistico_politica` (ningún item)
1. [x] `plan_parcial_urbanistico_politica` (ningún item)
1. [x] `modificacion_urbanistico_politica` (ningún item)
1. [x] `proyecto_urbanistico_politica` (ningún item)
1. [x] `licencia_urbanistico_politica` (ningún item)
1. [x] `otros_urbanistico_politica` (ningún item)
1. [x] `recursos_interpuestos` (1 item, texto largo)
1. [x] `sentencias_judiciales` (texto largo)
1. [x] `n_fecha_sentencias` 
1. [x] `tribunal_dicta` (2 items. No sé si usar taxonomía libre o texto corto)
1. [x] `fallo`  (1 item lo usa. Texto largo)
1. [x] `hipoteca_cargas`  (1 item lo usa. Texto largo)
1. [x] `cuantia_hipoteca`  (número)
1. [x] `concurso_acreedores`  (3 item usa este campo. Texto largo, es algo confuso su contenido)
1. [x] `entidades_financieras`  (2 items. Taxonomía de valores múltiples)
1. [x] `figuras_proteccion_ambiental` (2 elemento usa este campo, parece que se solapa con el campo `zonificacion_nivel_proteccion` , campo de texto largo )
1. [x] `nombre_figuras_proteccion_ambiental` (ningún item usa este campo)
1. [x] `zonificacion_nivel_proteccion` (2 items lo utilizan, campo de texto largo)
1. [x] `dominio_publico` (Solo un item tiene un valor)
1. [x] `enlaces_noticias`
1. [x] `material_grafico` Estudiar opción de fusionar con archivos_adjuntos
1. [x] `archivos_adjuntos`

1. [x] Additionally all the contents should be assigned a default value for `field_corpse_category = "Adopted"`

**Comment by ccamara** [comment]
Initial work has been done on this issue, but all fields from #5 need to be mapped. Put on hold till #5  is closed.

**Comment by ccamara** [comment]
Unit measure fields cannot be migrated using feeds (visit https://www.drupal.org/node/2664492)

**Comment by numeroteca** [comment]
We have 2 types of corpses:
- desenterrados
 + bases de datos previas. Files: `bases_datos_previas.geojson`, `error_de_sistema.geojson` and `especulacionecologistas.geojson`. `bases_datos_previas.geojson` has location, source of information and description. `error_de_sistema.geojson` and `especulacionecologistas.geojson` should be merged with `bases_datos_previas.geojson` with the same data structure.
 + a través de formulario desentierra_cadaver_160125.geojson
- adoptados base_datos_cadaveres_inmobiliarios_160202.geojson (note that I don't make distinction here between "normales" and "premium"). I am preparing that geojson manually from the drive spreadsheet once every month or two months.

All files available at https://github.com/cadaveresinmob/adoptamap/tree/master/data
Information: [how geojson of previous databases was made](https://groups.google.com/forum/#!msg/hacia-base-datos-inmobiliaria/wWazj53UK8Y/EKDZorTsenAJ).

Problems:

- Some locations are duplicated, as exitisng previous databases had the same locations. The cleaning process of those data bases has not been completed.
- Some locations of previous databases are not corpses. Some have been cleaned, but not entirely.

So I envision: the new website will have all the adoptados. The desenterrados will be points of a different kind in the map that can be edited: when you fill enough information (we have to define what) they become adoptados.

**Comment by ccamara** [comment]
Thanks for your clarifications, @numeroteca . This issue refers to the "adoptados" (although it will also work with the data coming from Nación Rotonda) as each dataset has different row names and hence a different parser is needed. 

I talked to @skotperez and he was going to study all the data sources in order to decide whether it's better to change them (and clean the data -as some of them have html tags or information that can't be parsed as it is stored) in order to fit this parser or clean them and create a specific parser for each data source. If we finally use this approach we should definitely create a new issue, as the parser will be completely different from this one.

In order to get the latest data from "Cadáveres adoptados" I am using [this R script](https://github.com/ccamara/c_inmobiliarios_data) which connects to google drive, fetches data from all the tabs, puts them together and splits latitude and longitude in different columns so they can be parsed and saves a csv file. This is to say that we can get the latest data at any time we want in an automated way, although I didn't do anything for the desenterrados ones (although it also works with the data from Nación Rotonda, as they have the same row names), so your links will be really helpful. 

> Problems:
>
>  Some locations are duplicated, as exitisng previous databases had the same locations. The cleaning process of those data bases has not been completed.
>
>    Some locations of previous databases are not corpses. Some have been cleaned, but not entirely.

Yes, we have two big problems here.

As for the first one, I have used the following workaround:
* I marked "promotional name" to be unique, so if we had two rows with the same field name, the second would update the first information. Provided they do not have contradictory information, we would get the information which would be the sum of the two instances. 

I could mark other fields to be unique, if we want. But it would always be better to make a cleanup of the data first.
Once the data has been imported, and in order to prevent future duplicates, we should make something different (eg: we can set up a field to be unique with unique_field module, so if anyone wants to create a new corpse with the same name, or we can study using this other option)

As for the second one I'm afraid we should clean data sources first. Or later (as we can always delete drupal nodes -if you have a user with the right permissions, which makes me think I should create a new issue for that) 

> So I envision: the new website will have all the adoptados. The desenterrados will be points of a different kind in the map that can be edited: when you fill enough information (we have to define what) they become adoptados.

I agree. As I created an extra field #27 for this purpose, I should make that all the corpses from the "Adoptados" data source are added as "Adoptados" by adding a new column with "Adoptados" value and then mapping to the corresponding field (`field_corpse_category`)

> ... when you fill enough information (we have to define what) they become adoptados.

Agree as well. I should create a new issue for that too, and study the best solution to automate that (maybe using rules)

**Comment by numeroteca** [comment]
Quizás no quedó claro en mi anterior mensaje, creo que no haría falta que @skotperez revisara las bases de datos previas:

All the **bases de datos previas** have already been merged in one file `bases_datos_previas.geojson`. All of the locations same row headers: name of the location (lat an long), source of information and description. It remains to be put together with the locations from Error de sistema (`error_de_sistema.geojson`) and Ecologistas en Acción (`especulacionecologistas.geojson`). So I think there is no need to parse them.

[I described the process in the email group](https://groups.google.com/forum/#!searchin/hacia-base-datos-inmobiliaria/neoruinas/hacia-base-datos-inmobiliaria/wWazj53UK8Y/EKDZorTsenAJ). Some locations were not properly geolocated by Google fusion tables, but I think we got most of it.


As the file from Nación Rotonda is constantly updated it will need another solution.

Files are available at https://github.com/cadaveresinmob/adoptamap/tree/master/data

**Comment by ccamara** [comment]
Closing issue as all fields have been mapped.
